http:
  port: ':8080'
  timeout: '30s'
  shutdown_timeout: '30s'
  read_timeout: '15s'
  write_timeout: '60s'

db:
  host: 'db'
  port: '5432'
  db_name: 'task-management'
  username: 'postgres'
  password: 'postgres'
  migration_path: 'migrations/pg'
  migration_version: 1

token:
  time_to_live: "59m"
  token_secret_key: "asdfdsa"