version: '3.8'

services:
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=task-management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5438:5432

  app:
    build: ./
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; ./task-management'
    ports:
      - 8080:8080
    depends_on:
      - db